include(joinpath(@__DIR__, "..", "src", "CiroPVHC.jl"))

using .CiroPVHC

function rounded(value::Real; digits::Int=4)
    return isfinite(Float64(value)) ? string(round(Float64(value); digits=digits)) : "unavailable"
end

function joined(values)
    return isempty(values) ? "[]" : "[" * join(values, ", ") * "]"
end

config = S2UnmanagedEVConfig()
result = solve_s2_unmanaged_ev(config)

println("CiroPVHC S2 PV + unmanaged EV paper-policy final snapshot")
println("benchmark_data: MATPOWER case33bw loads/impedances; raw MATPOWER branch ratings remain unchanged and missing.")
println("paper_study_assumptions:")
println("  selected_time_rule: maximum PV profile")
println("  voltage_bounds_pu: [$(config.vmin_pu), $(config.vmax_pu)]")
println("  synthetic_active_branch_smax_kva: $(config.synthetic_smax_kva)")
println("  synthetic_current_limit: ell <= (Smax/baseMVA)^2 at nominal 1.0 pu voltage")
println("  pv_candidate_limit_kw_per_unit: $(config.pv_limit_kw)")
println("  no_upstream_export: true")
println("  curtailment_budget_alpha: $(config.alpha_cur)")
println("  beta_loss: $(config.beta_loss)")
println("  unmanaged_ev_charging: fixed active and reactive demand, not optimized")
println("  s1_locked_hc_baseline_kw: $(config.s1_hc_baseline_kw)")
println("scenario_name: $(result.scenario_name)")
println("selected_time_index: $(result.selected_time_index)")
println("ev_penetration_scale: $(rounded(result.ev_penetration_scale; digits=4))")
println("EVCS_buses: $(joined(result.evcs_buses))")
println("base_load_kw: $(rounded(result.base_load_kw))")
println("unmanaged_ev_load_kw: $(rounded(result.unmanaged_ev_load_kw))")
println("total_load_kw: $(rounded(result.total_load_kw))")
println("total_ev_reactive_power_kvar: $(rounded(result.total_ev_reactive_power_kvar))")
println("stage1_termination_status: $(result.stage1_termination_status)")
println("stage2_termination_status: $(result.stage2_termination_status)")
println("stage1_hc_kw: $(rounded(result.stage1_hc_kw))")
println("stage2_accepted_hc_kw: $(rounded(result.stage2_accepted_hc_kw))")
println("total_pv_available_kw: $(rounded(result.total_pv_available_kw))")
println("total_pv_injected_kw: $(rounded(result.total_pv_injected_kw))")
println("total_pv_curtailed_kw: $(rounded(result.total_pv_curtailed_kw))")
println("PV_curtailment_percentage: $(rounded(result.pv_curtailment_percentage))")
println("substation_active_power_kw: $(rounded(result.substation_active_power_kw))")
println("substation_reactive_power_kvar: $(rounded(result.substation_reactive_power_kvar))")
println("network_losses_kw: $(rounded(result.network_losses_kw))")
println("loss_percentage: $(rounded(result.loss_percentage))")
println("voltage_min: $(rounded(result.voltage_min; digits=5))")
println("voltage_max: $(rounded(result.voltage_max; digits=5))")
println("voltage_min_bus: $(result.voltage_min_bus)")
println("voltage_max_bus: $(result.voltage_max_bus)")
println("max_line_loading: $(rounded(result.max_line_loading; digits=5))")
println("max_line_loading_branch: $(result.max_line_loading_branch)")
println("max_current_loading: $(rounded(result.max_current_loading; digits=5))")
println("max_current_loading_branch: $(result.max_current_loading_branch)")
println("active_limiting_constraints: $(joined(result.active_limiting_constraints))")
println("result_classification: $(result.result_classification)")
println("physical_validity_flag: $(result.physical_validity_flag)")
println("S1_vs_S2_comparison:")
println("  s1_baseline_hc_kw: $(rounded(result.s1_baseline_hc_kw))")
println("  s1_baseline_losses_kw: $(rounded(result.s1_baseline_losses_kw))")
println("  s1_baseline_voltage_min: $(rounded(result.s1_baseline_voltage_min; digits=5))")
println("  s1_baseline_max_line_loading: $(rounded(result.s1_baseline_max_line_loading; digits=5))")
println("  delta_HC_kw: $(rounded(result.delta_HC_kw))")
println("  delta_HC_percent: $(rounded(result.delta_HC_percent))")
println("  delta_losses_kw: $(rounded(result.delta_losses_kw))")
println("  delta_voltage_min: $(rounded(result.delta_voltage_min; digits=5))")
println("  delta_max_line_loading: $(rounded(result.delta_max_line_loading; digits=5))")
